### ISSUE TITLE
The GX701 layout doesn't seem to be the correct one.

### ISSUE THREAD

**Issue by UndeadKernel** [iamkroot/asus-numpad#10]
I have a Zephyrus S GX701 and noticed that after installing the `asus-numpad` service, the layout was not the right one.

The original (python) repository defines the layout in [this file](https://github.com/mohamed-badaoui/asus-touchpad-numpad-driver/blob/main/numpad_layouts/gx701.py). Your definition of the GX701 layout, found [in here](https://github.com/iamkroot/asus-numpad/blob/master/src/numpad_layout.rs#L243), does not match the original (and correct) one.

Was the change to the GX701 layout intentional?

**Comment by iamkroot** [comment]
That looks like a copy-paste error on my part. I must have copied the `ux581` layout and forgotten to update it for gx701. Would you like to raise a PR with the correct one?

**Comment by UndeadKernel** [comment]
Sure thing, I'll post a Pull Request as I already have the correct layout.
Though, I need a couple of hours to be back home.

**Comment by UndeadKernel** [comment]
I've addressed this issue in the PR #11 .
