### ISSUE TITLE
up5401ea Support

### ISSUE THREAD

**Issue by Tahinli** [iamkroot/asus-numpad#19]
Hi, if you don't mind can you add support for up5401ea, you can check layout in https://github.com/asus-linux-drivers/asus-numberpad-driver  . Thanks

This Rust implementation is really really working better then python one for me. But my layout is not in this project. I can be a tester or something, if you need.

**Comment by Tahinli** [comment]
okay, problem is different and i noticed now. i checked M433I layout and it's same as mine. check the code and saw the layout is also correct. then i realize why output is different, my keyboard layout is problem. normally my keyboard is Turkish Q and i changed my layout to the English UK, driver works perfectly. So i will close this issue and open new one. Most probably we can fix the code with making it staying always same keyboard or detect systems keyboard layout. second solution is pretty painful i think, that's why first solution is much better i think.

This problem can be happened in other keyboard layouts.

**Comment by iamkroot** [comment]
Question- does https://github.com/asus-linux-drivers/asus-numberpad-driver work properly for you? I'm seeing that they have the same layout defined in https://github.com/asus-linux-drivers/asus-numberpad-driver/blob/master/numpad_layouts/up5401ea.py as ours.

Edit: Ah, looks like they call X11 to get the proper key codes-
https://github.com/asus-linux-drivers/asus-numberpad-driver/blob/fc78b5c06ca161d8d316a6b07b13445cc81a5369/asus_touchpad.py#L365-L392
