### ISSUE TITLE
Need to restart daemon after system reboot

### ISSUE THREAD

**Issue by encrustace** [iamkroot/asus-numpad#6]
After every boot, it requires to give the below command to work
`sudo systemctl status asus-numpad.service`

moved asus-numpad to /usr/bin
in /etc/xdg/asus_numpad.toml
```
layout = "M433IA"
calc_start_command = ["KEY_CALC"]
calc_stop_command = {cmd = "killall", args = ["gnome-calculator"]}
disable_numlock_on_start = false
```

**Daemon status after reboot:**

 asus-numpad.service - Asus Numpad Driver
     Loaded: loaded (/etc/systemd/system/asus-numpad.service; enabled; preset: disabled)
     Active: active (running) since Tue 2022-08-02 00:17:13 IST; 52s ago
   Main PID: 3644 (asus-numpad)
      Tasks: 1 (limit: 18811)
     Memory: 348.0K
        CPU: 343ms
     CGroup: /system.slice/asus-numpad.service
             └─3644 /usr/bin/asus-numpad

Aug 02 00:17:13 zenbook systemd[1]: Started Asus Numpad Driver.

**Note:** Not created separate user and user group

**System Conf:**
OS: Arch Linux x86_64 
Host: ZenBook UX325EA_UX325EA 1.0 
Kernel: 5.18.15-arch1-1

**Comment by iamkroot** [comment]
That seems weird, the `status` command doesn't really do much except showing the current info. Are you sure your DE isn't messing with the numlock? Try setting `disable_numlock_on_start = true` and restart.

**Comment by encrustace** [comment]
It is true, but still the same problem, by the way, I am using gnome with Wayland.

**Comment by encrustace** [comment]
Tried with xorg also but still same problem

**Comment by iamkroot** [comment]
Could you check if https://github.com/mohamed-badaoui/asus-touchpad-numpad-driver is working?

**Comment by iamkroot** [comment]
Even I started getting this bug after some Manjaro update. I've made a change to the systemd service file increasing the Restart timeout, which seems to fix it for me. Could you please try with the latest version from master?

**Comment by encrustace** [comment]
I will let you know

**Comment by iamkroot** [comment]
Note: More than anything, you'll need to update the systemd service file at `/etc/systemd/system/asus-numpad.service` to the new version at https://github.com/iamkroot/asus-numpad/blob/master/tools/asus-numpad.service

**Comment by encrustace** [comment]
Yes, I have increased the time to 2 sec and now it is working,

Thank You for your effort
